### ISSUE TITLE
Minimal Working Example yields error

### ISSUE THREAD

**Issue by chreliot** [ypid/latex-packages#1]
Running the following minimal example (I think from the package author, via SE) yields the following error: 

  Latex Error: ./runLicense.tex:9 LaTeX Error: File `doclicense-CC-by-nc-sa' not found.

    \documentclass{article}
    \usepackage{hyperref}
    \usepackage[
        type={CC},
        modifier={by-nc-sa},
        version={3.0},
    ]{doclicense}
    \begin{document}
    \doclicenseThis
    \end{document}

I'm using a current version of TeXLive/MacTeX.

Complete error log follows:

This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=pdflatex 2015.1.14)  19 APR 2015 21:29
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**runLicense.tex
(./runLicense.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 79 languages loaded.
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@section=\count80
\c@subsection=\count81
\c@subsubsection=\count82
\c@paragraph=\count83
\c@subparagraph=\count84
\c@figure=\count85
\c@table=\count86
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/hyperref.sty
Package: hyperref 2012/11/06 v6.83m Hypertext links for LaTeX

(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
Package: hobsub-hyperref 2012/05/28 v1.13 Bundle oberdiek, subset hyperref (HO)

(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty
Package: hobsub-generic 2012/05/28 v1.13 Bundle oberdiek, subset generic (HO)
Package: hobsub 2012/05/28 v1.13 Construct package bundles (HO)
Package: infwarerr 2010/04/08 v1.3 Providing info/warning/error messages (HO)
Package: ltxcmds 2011/11/09 v1.22 LaTeX kernel commands for general use (HO)
Package: ifluatex 2010/03/01 v1.3 Provides the ifluatex switch (HO)
Package ifluatex Info: LuaTeX not detected.
Package: ifvtex 2010/03/01 v1.5 Detect VTeX and its facilities (HO)
Package ifvtex Info: VTeX not detected.
Package: intcalc 2007/09/27 v1.1 Expandable calculations with integers (HO)
Package: ifpdf 2011/01/30 v2.3 Provides the ifpdf switch (HO)
Package ifpdf Info: pdfTeX in PDF mode is detected.
Package: etexcmds 2011/02/16 v1.5 Avoid name clashes with e-TeX commands (HO)
Package etexcmds Info: Could not find \expanded.
(etexcmds)             That can mean that you are not using pdfTeX 1.50 or
(etexcmds)             that some package has redefined \expanded.
(etexcmds)             In the latter case, load this package earlier.
Package: kvsetkeys 2012/04/25 v1.16 Key value parser (HO)
Package: kvdefinekeys 2011/04/07 v1.3 Define keys (HO)
Package: pdftexcmds 2011/11/29 v0.20 Utility functions of pdfTeX for LuaTeX (HO
)
Package pdftexcmds Info: LuaTeX not detected.
Package pdftexcmds Info: \pdf@primitive is available.
Package pdftexcmds Info: \pdf@ifprimitive is available.
Package pdftexcmds Info: \pdfdraftmode found.
Package: pdfescape 2011/11/25 v1.13 Implements pdfTeX's escape features (HO)
Package: bigintcalc 2012/04/08 v1.3 Expandable calculations on big integers (HO
)
Package: bitset 2011/01/30 v1.1 Handle bit-vector datatype (HO)
Package: uniquecounter 2011/01/30 v1.2 Provide unlimited unique counter (HO)
)
Package hobsub Info: Skipping package `hobsub' (already loaded).
Package: letltxmacro 2010/09/02 v1.4 Let assignment for LaTeX macros (HO)
Package: hopatch 2012/05/28 v1.2 Wrapper for package hooks (HO)
Package: xcolor-patch 2011/01/30 xcolor patch
Package: atveryend 2011/06/30 v1.8 Hooks at the very end of document (HO)
Package atveryend Info: \enddocument detected (standard20110627).
Package: atbegshi 2011/10/05 v1.16 At begin shipout hook (HO)
Package: refcount 2011/10/16 v3.4 Data extraction from label references (HO)
Package: hycolor 2011/01/30 v1.7 Color options for hyperref/bookmark (HO)
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks14
)
(/usr/local/texlive/2014/texmf-dist/tex/generic/ifxetex/ifxetex.sty
Package: ifxetex 2010/09/12 v0.6 Provides ifxetex conditional
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/auxhook.sty
Package: auxhook 2011/03/04 v1.3 Hooks for auxiliary files (HO)
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/kvoptions.sty
Package: kvoptions 2011/06/30 v3.11 Key value format for package options (HO)
)
\@linkdim=\dimen103
\Hy@linkcounter=\count87
\Hy@pagecounter=\count88

(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/pd1enc.def
File: pd1enc.def 2012/11/06 v6.83m Hyperref: PDFDocEncoding definition (HO)
)
\Hy@SavedSpaceFactor=\count89

(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/hyperref.cfg
File: hyperref.cfg 2002/06/06 v1.2 hyperref configuration of TeXLive
)
Package hyperref Info: Hyper figures OFF on input line 4443.
Package hyperref Info: Link nesting OFF on input line 4448.
Package hyperref Info: Hyper index ON on input line 4451.
Package hyperref Info: Plain pages OFF on input line 4458.
Package hyperref Info: Backreferencing OFF on input line 4463.
Package hyperref Info: Implicit mode ON; LaTeX internals redefined.
Package hyperref Info: Bookmarks ON on input line 4688.
\c@Hy@tempcnt=\count90

(/usr/local/texlive/2014/texmf-dist/tex/latex/url/url.sty
\Urlmuskip=\muskip10
Package: url 2013/09/16  ver 3.4  Verb mode for urls, etc.
)
LaTeX Info: Redefining \url on input line 5041.
\XeTeXLinkMargin=\dimen104
\Fld@menulength=\count91
\Field@Width=\dimen105
\Fld@charsize=\dimen106
Package hyperref Info: Hyper figures OFF on input line 6295.
Package hyperref Info: Link nesting OFF on input line 6300.
Package hyperref Info: Hyper index ON on input line 6303.
Package hyperref Info: backreferencing OFF on input line 6310.
Package hyperref Info: Link coloring OFF on input line 6315.
Package hyperref Info: Link coloring with OCG OFF on input line 6320.
Package hyperref Info: PDF/A mode OFF on input line 6325.
LaTeX Info: Redefining \ref on input line 6365.
LaTeX Info: Redefining \pageref on input line 6369.
\Hy@abspage=\count92
\c@Item=\count93
\c@Hfootnote=\count94
)

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/hpdftex.def
File: hpdftex.def 2012/11/06 v6.83m Hyperref driver for pdfTeX
\Fld@listcount=\count95
\c@bookmark@seq@number=\count96

(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty
Package: rerunfilecheck 2011/04/15 v1.7 Rerun checks for auxiliary files (HO)
Package uniquecounter Info: New unique counter `rerunfilecheck' on input line 2
82.
)
\Hy@SectionHShift=\skip43
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/doclicense/doclicense.sty
Package: doclicense 2015/04/06 v1.1 Support for putting documents under a licen
se

(/usr/local/texlive/2014/texmf-dist/tex/latex/xifthen/xifthen.sty
Package: xifthen 2009/04/17 v1.3 Extended ifthen features

(/usr/local/texlive/2014/texmf-dist/tex/latex/etex-pkg/etex.sty
Package: etex 2015/03/02 v2.1 eTeX basic definition package (PEB,DPC)
\et@xins=\count97
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/tools/calc.sty
Package: calc 2014/10/28 v4.3 Infix arithmetic (KKT,FJ)
\calc@Acount=\count98
\calc@Bcount=\count99
\calc@Adimen=\dimen107
\calc@Bdimen=\dimen108
\calc@Askip=\skip44
\calc@Bskip=\skip45
LaTeX Info: Redefining \setlength on input line 75.
LaTeX Info: Redefining \addtolength on input line 76.
\calc@Ccount=\count100
\calc@Cskip=\skip46
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/base/ifthen.sty
Package: ifthen 2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/ifmtarg/ifmtarg.sty
Package: ifmtarg 2009/09/02 v1.2a check for an empty argument
))
(/usr/local/texlive/2014/texmf-dist/tex/latex/etoolbox/etoolbox.sty
Package: etoolbox 2015/03/19 v2.1d e-TeX tools for LaTeX (JAW)
\etb@tempcnta=\count101
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/tools/xspace.sty
Package: xspace 2014/10/28 v1.13 Space after command names (DPC,MH)
)
\doclicense@hsize=\skip47

(/usr/local/texlive/2014/texmf-dist/tex/latex/doclicense/doclicense-english.ldf
File: doclicense-english.ldf 
)) (/usr/local/texlive/2014/texmf-dist/tex/latex/csquotes/csquotes.sty
Package: csquotes 2011/10/22 v5.1d context-sensitive quotations
\csq@reset=\count102
\csq@gtype=\count103
\csq@glevel=\count104
\csq@qlevel=\count105
\csq@maxlvl=\count106
\csq@tshold=\count107
\csq@ltx@everypar=\toks15

(/usr/local/texlive/2014/texmf-dist/tex/latex/csquotes/csquotes.def
File: csquotes.def 2011/10/22 v5.1d csquotes generic definitions
)
Package csquotes Info: Trying to load configuration file 'csquotes.cfg'...
Package csquotes Info: ... configuration file loaded successfully.

(/usr/local/texlive/2014/texmf-dist/tex/latex/csquotes/csquotes.cfg
File: csquotes.cfg 
))
(/usr/local/texlive/2014/texmf-dist/tex/latex/ccicons/ccicons.sty
Package: ccicons 2013/04/16 v1.5 LaTeX support for Creative Commons icons

(/usr/local/texlive/2014/texmf-dist/tex/latex/xkeyval/xkeyval.sty
Package: xkeyval 2014/12/03 v2.7a package option processing (HA)

(/usr/local/texlive/2014/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2014/texmf-dist/tex/generic/xkeyval/xkvutils.tex
\XKV@toks=\toks16
\XKV@tempa@toks=\toks17
)
\XKV@depth=\count108
File: xkeyval.tex 2014/12/03 v2.7a key=value parser (HA)
)))
(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/graphicx.sty
Package: graphicx 2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)

(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/graphics.sty
Package: graphics 2014/10/28 v1.0p Standard LaTeX Graphics (DPC,SPQR)

(/usr/local/texlive/2014/texmf-dist/tex/latex/graphics/trig.sty
Package: trig 1999/03/16 v1.09 sin cos tan (DPC)
)
(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/graphics.cfg
File: graphics.cfg 2010/04/23 v1.9 graphics configuration of TeX Live
)
Package graphics Info: Driver file: pdftex.def on input line 91.

(/usr/local/texlive/2014/texmf-dist/tex/latex/pdftex-def/pdftex.def
File: pdftex.def 2011/05/27 v0.06d Graphics/color for pdfTeX
\Gread@gobject=\count109
))
\Gin@req@height=\dimen109
\Gin@req@width=\dimen110
)
(./runLicense.aux)
\openout1 = `runLicense.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 8.
LaTeX Font Info:    ... okay on input line 8.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 8.
LaTeX Font Info:    ... okay on input line 8.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 8.
LaTeX Font Info:    ... okay on input line 8.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 8.
LaTeX Font Info:    ... okay on input line 8.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 8.
LaTeX Font Info:    ... okay on input line 8.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 8.
LaTeX Font Info:    ... okay on input line 8.
LaTeX Font Info:    Checking defaults for PD1/pdf/m/n on input line 8.
LaTeX Font Info:    ... okay on input line 8.
\AtBeginShipoutBox=\box26
Package hyperref Info: Link coloring OFF on input line 8.

(/usr/local/texlive/2014/texmf-dist/tex/latex/hyperref/nameref.sty
Package: nameref 2012/10/27 v2.43 Cross-referencing by name of section

(/usr/local/texlive/2014/texmf-dist/tex/generic/oberdiek/gettitlestring.sty
Package: gettitlestring 2010/12/03 v1.4 Cleanup title references (HO)
)
\c@section@level=\count110
)
LaTeX Info: Redefining \ref on input line 8.
LaTeX Info: Redefining \pageref on input line 8.
LaTeX Info: Redefining \nameref on input line 8.

(./runLicense.out) (./runLicense.out)
\@outlinefile=\write3
\openout3 = `runLicense.out'.

(/usr/local/texlive/2014/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
\scratchcounter=\count111
\scratchdimen=\dimen111
\scratchbox=\box27
\nofMPsegments=\count112
\nofMParguments=\count113
\everyMPshowfont=\toks18
\MPscratchCnt=\count114
\MPscratchDim=\dimen112
\MPnumerator=\count115
\makeMPintoPDFobject=\count116
\everyMPtoPDFconversion=\toks19
) (/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
Package: epstopdf-base 2010/02/09 v2.5 Base part for package epstopdf

(/usr/local/texlive/2014/texmf-dist/tex/latex/oberdiek/grfext.sty
Package: grfext 2010/08/19 v1.1 Manage graphics extensions (HO)
)
Package grfext Info: Graphics extension search list:
(grfext)             [.png,.pdf,.jpg,.mps,.jpeg,.jbig2,.jb2,.PNG,.PDF,.JPG,.JPE
G,.JBIG2,.JB2,.eps]
(grfext)             \AppendGraphicsExtensions on input line 452.

(/usr/local/texlive/2014/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg
File: epstopdf-sys.cfg 2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Liv
e
))
Underfull \hbox (badness 1655) in paragraph at lines 9--9
[]\OT1/cmr/m/n/10 This work is li-censed un-der a []Cre-ative Com-
 []

LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <7> on input line 9.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <5> on input line 9.

./runLicense.tex:9: LaTeX Error: File `doclicense-CC-by-nc-sa' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9   \doclicenseThis
                     
I could not locate the file with any of these extensions:
.png,.pdf,.jpg,.mps,.jpeg,.jbig2,.jb2,.PNG,.PDF,.JPG,.JPEG,.JBIG2,.JB2,.eps
Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

Package atveryend Info: Empty hook `BeforeClearDocument' on input line 10.
[1

{/usr/local/texlive/2014/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
Package atveryend Info: Empty hook `AfterLastShipout' on input line 10.

(./runLicense.aux)
Package atveryend Info: Executing hook `AtVeryEndDocument' on input line 10.
Package atveryend Info: Executing hook `AtEndAfterFileList' on input line 10.
Package rerunfilecheck Info: File `runLicense.out' has not changed.
(rerunfilecheck)             Checksum: D41D8CD98F00B204E9800998ECF8427E;0.
Package atveryend Info: Empty hook `AtVeryVeryEnd' on input line 10.
 ) 
Here is how much of TeX's memory you used:
 6432 strings out of 493109
 96158 string characters out of 6135004
 189397 words of memory out of 5000000
 9830 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 30i,4n,46p,933b,367s stack positions out of 5000i,500n,10000p,200000b,80000s
</usr/local/texlive/2014/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>

Output written on runLicense.pdf (1 page, 17101 bytes).
PDF statistics:
 21 PDF objects out of 1000 (max. 8388607)
 16 compressed objects within 1 object stream
 2 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

**Comment by ypid** [comment]
I can not replicate the problem you described. Can you search your TEXMF tree for the file doclicense-
CC-by-nc-sa.pdf and send me the location? If it is not there try downloading the zip from ctan and extract it into your local TEXMF tree. https://ctan.org/tex-archive/macros/latex/contrib/doclicense

**Comment by chreliot** [comment]
Hi, Thank you. Downloading and installing the zip from CTAN permits that MWE to compile. However, 
(a)  I suppose that means that the version in TeXLive doesn't include the image files; and
(b) Even with the download the following does not compile:

Error: Latex Error: ./runLicense.tex:9 Package doclicense Error: Icon not defined.

  \documentclass{article}
  \usepackage{hyperref}
  \usepackage[
      type={CC},
      modifier={by},
      version={4.0},
  ]{doclicense}
  \begin{document}
  Icons:  \doclicenseIcon
  \end{document}

**Comment by ypid** [comment]
> Error: Latex Error: ./runLicense.tex:9 Package doclicense Error: Icon not defined.

Thanks, fixed it. The Icon command was not enough tested. I wrote a [short test script](https://github.com/ypid/latex-packages/blob/master/doclicense/run_tests) to test all options.

>  I suppose that means that the version in TeXLive doesn't include the image files

That is possible …
Are you using the standalone TexLive DVD or a package from a linux distro?
And what files are already present? Please profile the output of the `tree` command or `ls -l --recursive` or similar of the doclicense directory of TexLive.

**Comment by chreliot** [comment]
I'm using a continually-updated MacTeX distribution of TeXLive from TUG at https://tug.org/mactex/

At /usr/local/texlive/2014/texmf-dist/doc/latex/doclicense

Output of `ls -l -R` is

    total 592
    -rw-r--r--   1 root  wheel    1307 Apr  6 17:35 README
    -rw-r--r--   1 root  wheel  295658 Apr  6 17:35 doclicense.pdf
    drwxr-xr-x  12 root  wheel     408 Apr 16 21:35 images
    
    ./images:
    total 176
    -rw-r--r--  1 root  wheel  6648 Feb  7 18:06 doclicense-CC-by-nc-eu.pdf
    -rw-r--r--  1 root  wheel  7554 Feb  7 18:06 doclicense-CC-by-nc-nd-eu.pdf
    -rw-r--r--  1 root  wheel  8360 Feb  7 18:06 doclicense-CC-by-nc-sa-eu.pdf
    -rw-r--r--  1 root  wheel  8295 Feb  6 18:29 doclicense-CC-by-nc-sa.pdf
    -rw-r--r--  1 root  wheel  6561 Feb  6 18:29 doclicense-CC-by-nc.pdf
    -rw-r--r--  1 root  wheel  5990 Feb  6 18:29 doclicense-CC-by-nd.pdf
    -rw-r--r--  1 root  wheel  6758 Feb  6 18:29 doclicense-CC-by-sa.pdf
    -rw-r--r--  1 root  wheel  5022 Feb  6 18:29 doclicense-CC-by.pdf
    -rw-r--r--  1 root  wheel  4288 Feb  6 18:29 doclicense-CC-pd.pdf
    -rw-r--r--  1 root  wheel  4616 Feb  6 18:29 doclicense-CC-zero.pdf
    
Does that help at all?

**Comment by ypid** [comment]
It seems that the images ended up in the wrong directory: `doc/latex` I guess LaTeX does not look for images to include there. I will have to check that.

**Comment by chreliot** [comment]
Thank you for your work on this useful package. I will test it again if I see an update appear through TeXLive.

**Comment by kakila** [comment]
Hi,

I am hitting the same error: 

     File `doclicense-CC-by-sa' not found.

the output of `locate doclicense-CC-by-sa` is

    /usr/local/texlive/2014/texmf-dist/doc/latex/doclicense/images/doclicense-CC-by-sa.pdf

and `which latex` gives
   
    /usr/local/texlive/2014/bin/x86_64-linux/latex

finally `tlmgr --version` responds with
    
    tlmgr revision 37738 (2015-07-03 01:10:09 +0200)
    tlmgr using installation: /usr/local/texlive/2014
    TeX Live (http://tug.org/texlive) version 2014

**Comment by ypid** [comment]
Version of doclicense?

**Comment by kakila** [comment]
`tlmgr info doclicense` says:

    package:     doclicense
    category:    Package
    shortdesc:   Support for putting documents under a license
    longdesc:    This package allows you to put your document under a license and include a link to read about the license or include an icon or image of the license. Currently, only Creative Commons is supported, but this package is designed to handle all kinds of licenses.
    installed:   Yes
    revision:    38049
    sizes:       src: 29k, doc: 389k, run: 69k
    relocatable: No
    cat-version: 1.3
    cat-date:    2015-08-04 21:13:10 +0200
    cat-license: lppl1.3
    cat-topics:  licence-mgmt
    collection:  collection-latexextra

**Comment by ypid** [comment]
OK seems good. Thanks. Still an open issue which I tried to solve with 2721a0707e47d8e89a0b0062d2d4cc7b626696a9. I guess I need to contact the TeXLive maintainers now …

**Comment by kakila** [comment]
Is there a workaround? Like putting the pdf files in a particular folder, etc?

**Comment by ypid** [comment]
Sure. Just put the [doclicense](https://github.com/ypid/latex-packages/tree/master/doclicense) into your local TEXMF tree.

**Comment by ypid** [comment]
Can you give me a `ls -l -R /usr/local/texlive/2014/texmf-dist/tex/latex/doclicense/`?

**Comment by kakila** [comment]
Sure
```
/usr/local/texlive/2014/texmf-dist/tex/latex/doclicense/:
total 68
-rw-r--r-- 1 juanpi juanpi   69 Aug  5 22:13 doclicense-acadian.ldf
-rw-r--r-- 1 juanpi juanpi   71 Feb  7  2015 doclicense-american.ldf
-rw-r--r-- 1 juanpi juanpi   73 Feb  7  2015 doclicense-australian.ldf
-rw-r--r-- 1 juanpi juanpi   70 Feb  7  2015 doclicense-british.ldf
-rw-r--r-- 1 juanpi juanpi   71 Feb  7  2015 doclicense-canadian.ldf
-rw-r--r-- 1 juanpi juanpi   70 Aug  5 22:13 doclicense-canadien.ldf
-rw-r--r-- 1 juanpi juanpi 1449 Jun 23 01:43 doclicense-english.ldf
-rw-r--r-- 1 juanpi juanpi 1892 Aug  5 22:13 doclicense-french.ldf
-rw-r--r-- 1 juanpi juanpi 1842 Jun 23 01:43 doclicense-german.ldf
-rw-r--r-- 1 juanpi juanpi   73 Feb  7  2015 doclicense-newzealand.ldf
-rw-r--r-- 1 juanpi juanpi   69 Feb  7  2015 doclicense-ngerman.ldf
-rw-r--r-- 1 juanpi juanpi 1506 Jun 23 01:43 doclicense-spanish.ldf
-rw-r--r-- 1 juanpi juanpi 8275 Aug  5 22:13 doclicense.sty
-rw-r--r-- 1 juanpi juanpi   72 Feb 14  2015 doclicense-UKenglish.ldf
-rw-r--r-- 1 juanpi juanpi   72 Feb  7  2015 doclicense-USenglish.ldf
```

**Comment by ypid** [comment]
Thanks.

**Comment by ypid** [comment]
Tracked upstream: https://tug.org/pipermail/tex-live/2015-August/037302.html

**Comment by kakila** [comment]
Great! Thanks.

**Comment by ypid** [comment]
It got fixed :smile: `tlmgr update doclicense` should solve it.

    tlmgr: package repository http://mirror.unicorncloud.org/CTAN/systems/texlive/tlnet
    tlmgr: saving backups to /usr/local/texlive/2015/tlpkg/backups
    [1/1, ??:??/??:??] update: doclicense [343k] (36729 -> 38264) ... don

Confirmed with TeXlive 2015.

**Comment by kakila** [comment]
Confirmed with TeXlive 2014

**Comment by ypid** [comment]
Nice, thanks.

**Comment by chreliot** [comment]
Thank you for your work on this!

**Comment by projetmbc** [comment]
Thanks for the job. This works perfectly now ! That's great !
