### ISSUE TITLE
Essa >> Esta

### ISSUE THREAD

**Issue by leolca** [ypid/latex-packages#106]
https://github.com/ypid/latex-packages/blob/6c2d9c7f006339c657b230cb8709ab8224b48753/doclicense/doclicense-brazilian.ldf#L10

It should be written "Esta obra tem a licença", just as is in the doclicense-portuguese.ldf file.
As we are referring to "the present work", it should be used "esta" instead.

**Comment by ypid** [comment]
Thanks for the bug report and PR.
