### ISSUE TITLE
Incompatibility with spanish babel

### ISSUE THREAD

**Issue by Noitaenola** [ypid/latex-packages#11]
Using `doclicense` along `babel` with the `[spanish]` option makes LaTeX render `non breaking spaces` as `~` (literally).
Here is a MWE:

    \documentclass{article}

    \usepackage[spanish]{babel}
    \usepackage{doclicense}

    \begin{document}
    	\doclicenseNameRef
    \end{document}

![cc](https://cloud.githubusercontent.com/assets/16860001/12534399/8db4e3e0-c236-11e5-9101-faaf0fcc73bf.png)

I am using MikTeX 2.9 in windows 7x64.

**Comment by ypid** [comment]
Thanks very much for reporting. Fixed.
