### ISSUE TITLE
Option for hiding page numbers

### ISSUE THREAD

**Issue by omarz1** [ypid/latex-packages#15]
How about giving an option to hide the page number using `\thispagestyle{empty}`?

**Comment by ypid** [comment]
Sorry, I am not getting it. Can you explain for which macro and when this can come in handy?

**Comment by omarz1** [comment]
Well, I thought that this license declaration should come in a page alone, but I just found out that this is not part of the package. Choosing where it is placed and the style of the page it appears in is entirely up to the user. So, nothing to do here. Thanks.

**Comment by ypid** [comment]
No problem.
