### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by projetmbc** [ypid/latex-packages#2]
Hello.

Thanks for your job. I would like to contribute to the translation in French. Is there an easy way to do that ?

Do you know http://www.oneskyapp.com that is free for open source project ?

**Comment by ypid** [comment]
Translations are welcome, thanks …
I know that there are nice websites like transifex.net and [others](http://libreprojects.net/#scroll=development) for this but unfortunately, I am pretty sure that those websites don’t understand the file format used by doclicense but it should be possible to write a converter script for this task. I might look into this later and leave the issue open …

**Comment by projetmbc** [comment]
Can you give me an example of the file you use ? Maybe I can do a Python
script that change your format to a format for that websites and "vice
versa".


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French math teacher in a "Lycée" **and **Python **amateur developer*

2015-05-09 13:15 GMT+02:00 Robin Schneider <notifications@github.com>:

**Comment by ypid** [comment]
Sure a converter as python script is greatly appreciated. I quickly tried it with [transifex.net](transifex.net) and the key-value JSON format, but it did not accept the file. I would recommend [transifex.net](transifex.net) as platform but the data format is open to you when you want to give it a try. When you want to, you can use this [python script](https://github.com/hamcos/monitoring-scripts/blob/master/check_mk/wato_cvs_import.py) which I wrote a couple of weeks ago as an example for how OO and command line options can be done.

Please have a look at the updated [doclicense.pdf](https://github.com/ypid/latex-packages/raw/master/doclicense/doclicense.pdf) under contributing.

**Comment by projetmbc** [comment]
OK, I will clone your project and work on my own branch as soon as
possible, maybe monday.

Thanks for the help. ;-)


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French math teacher in a "Lycée" **and **Python **amateur developer*

2015-05-09 14:03 GMT+02:00 Robin Schneider <notifications@github.com>:

**Comment by ypid** [comment]
Thanks.

**Comment by ypid** [comment]
If you need an example how a translation can be added, check out #4.

**Comment by projetmbc** [comment]
Ok, the job seems easy. I just have to find a little time. Maybe this thursday.

**Comment by ypid** [comment]
Closed by #5.
