### ISSUE TITLE
Included quotes in russian translate of doclicense

### ISSUE THREAD

**Issue by bergentroll** [ypid/latex-packages#22]
In Russian we are using the french qoutes («») by default. But as included qoutes (as in russian version of \doclicenseThis macro) we are using the "paw" quotes like this: «Cafe ”Deca“». So what if doclicense will avoid to put namedefs in outer qoutes to keep only one deep level of quotation? Outer quotes seems unnecessary.

**Comment by ypid** [comment]
Not quite getting it unfortunately. Can you make a pull request?

**Comment by bergentroll** [comment]
Oh, I did not know where unwanted quotes pair come from, but now I see, that it is my own unnecessary quotes in the translation file. I made a pull request. Sorry for this.
