### ISSUE TITLE
doclicense: provide postscript images?

### ISSUE THREAD

**Issue by robertpetry** [ypid/latex-packages#25]
Compiling with the "latex" command to generate .dvi file fails with not being able to find missing "doclicense-CC-by" file.  This is not a path issue but rather the fact that it is looking for a postscript version of the image file.  My workaround was to find the doclicense-CC-by.pdf file and use pdf2ps to generate the corresponding postscript image and put that in the current directory.  In this case I was using the powerdot package to generate some slides and it requires this compilation method due to its pstricks dependency.  Likely the simplest method to resolve this is to include postscript along with the pdf images one imagines.

**Comment by ypid** [comment]
Interesting, even in 2018, there is still a need to have `.dvi` files and `latex` in the build pipeline. I had this once when using `pst-labo` [ref](https://ypid.wordpress.com/2012/01/28/168/) (German) but I decided to compile the graphics individually and convert them to a pdf. This does not work in this case. Also, powerdot seems be maintained still.

Addressed in #26. Can you review this and check if it works for you?

**Comment by ypid** [comment]
Works for me so I merged without feedback. Merged and released to CTAN. Thanks again for reporting!
