### ISSUE TITLE
CC by-nc-sa 3.0 image

### ISSUE THREAD

**Issue by projetmbc** [ypid/latex-packages#3]
The macro `\doclicenseImage` sends the following error under MacTeX.

    File 'doc-license-CC-by-nc-sa' not found.

**Comment by ypid** [comment]
Could be related to #1. What is interesting is that in your case there is a hyphen "doc-license". Please try it with the latest version from github.

**Comment by ypid** [comment]
This seems to be a problem in MacTeX. Do other CC modifiers like "by" work for you? Maybe you can investigate a little bit. I suspect that MacTeX moves all pdf files to the doc tree.

**Comment by ypid** [comment]
Any news so far?

**Comment by projetmbc** [comment]
Hello? I have updated MacTeX and the problem remains...

**Comment by ypid** [comment]
> Do other CC modifiers like "by" work for you?

> I suspect that MacTeX moves all pdf files to the doc tree.

Can you confirm that?

**Comment by projetmbc** [comment]
Can you give a minimal working example ?

**Comment by ypid** [comment]
Checkout https://tex.stackexchange.com/a/226788/32320 which is also mentioned in the documentation.

**Comment by ypid** [comment]
It got fixed in TeXlive. Can you try it again? https://github.com/ypid/latex-packages/issues/1#issuecomment-138340557

**Comment by ypid** [comment]
> Thanks for the job. This works perfectly now ! That's great !

Seems to work for you on Mac which is great. Do you want to close this issue?

**Comment by projetmbc** [comment]
Yes.

PS: what was the problem ?


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French math teacher in a "Lycée" **and **Python **amateur developer*

2015-09-07 22:40 GMT+02:00 Robin Schneider <notifications@github.com>:

**Comment by ypid** [comment]
Short description: https://tug.org/pipermail/tex-live/2015-August/037302.html
https://github.com/ypid/latex-packages/blob/036d0fed43b36e77a3e9f45c878f0cd5e03b5b43/doclicense/README#L38-L42

More details: #1

**Comment by projetmbc** [comment]
Thanks a lot.


*Christophe BAL*
*Enseignant de mathématiques en Lycée **et développeur Python amateur*
*---*
*French math teacher in a "Lycée" **and **Python **amateur developer*

2015-09-08 10:17 GMT+02:00 Robin Schneider <notifications@github.com>:
