### ISSUE TITLE
Make enumitem optional

### ISSUE THREAD

**Issue by jspitz** [ypid/latex-packages#40]
As of TeXLive 2019, doclicense loads enumitem. Alas, this makes it uncompilable with the beamer class (I use the doclicense package to create a copyright slide in my presentations).

Could you please make loading of enumitem optional (or even better, check if the beamer class is used, and if so, refrain from loading enumitem)?

**Comment by jspitz** [comment]
The pull request above implements this. I have not tested thoroughly, though.

**Comment by jspitz** [comment]
BTW if you only introduced `enumitem` to adjust the number style, another option would be to drop it completely and only use the `doclicense@enumitem` definition I have introduced for `enumitem=false`.
I can update my PR if required.

**Comment by ypid** [comment]
> BTW if you only introduced enumitem to adjust the number style, another option would be to drop it completely and only use the doclicense@enumitem definition I have introduced for enumitem=false.

Sounds good to me. Please do that. I tested #41 and I found no issues with the alternative fix.

**Comment by jspitz** [comment]
Done. Ready to merge.

**Comment by ypid** [comment]
Thanks very much!
