### ISSUE TITLE
doclicense: Wrong URL for pd license

### ISSUE THREAD

**Issue by sammaddens** [ypid/latex-packages#46]
The correct link for a `pd` license is **<https://creativecommons.org/licenses/publicdomain/deed.en>** instead of <https://creativecommons.org/licenses/publicdomain/1.0/deed.en>. So the version should be removed.

This can be easily solved by changing the code for `pd`.

````latex
    \ifthenelse{\equal{\doclicense@modifier}{pd}}{
      \renewcommand{\doclicense@icon}{\ccpd}
      \renewcommand{\doclicense@imagemodifier}{}
      \doclicense@setVersion[1.0]
      \edef\doclicenseURL{%
        \doclicense@baseUrlCC/%
        licenses/publicdomain%%COMMENT removed "/"
        \doclicense@UrlLangPart}%%COMMENT removed "\doclicense@versionUsed"
    }{}
````

**Comment by ypid** [comment]
Thanks @sammaddens, fixed it.

**Comment by ypid** [comment]
@sammaddens Note that CC PD is long retired. Refer to https://github.com/ypid/latex-packages/issues/53
