### ISSUE TITLE
doclicense: Breaks layout when in two column mode

### ISSUE THREAD

**Issue by NaoPross** [ypid/latex-packages#50]
First of all, nice work!

I have noticed that `\doclicenseThis` does not behave well in `twocolumn` mode, and I presume (I haven't tested) it's because you used [`\textwidth` instead of `\linewidth`](https://tex.stackexchange.com/questions/16942/difference-between-textwidth-linewidth-and-hsize) [here](https://github.com/ypid/latex-packages/blob/542c2973f7409d8c978827fe532d8afa558b9d15/doclicense/doclicense.dtx#L651-L652):

https://github.com/ypid/latex-packages/blob/542c2973f7409d8c978827fe532d8afa558b9d15/doclicense/doclicense.dtx#L651-L652

Example:
![twocol](https://user-images.githubusercontent.com/13507582/79641458-f9d8c800-8197-11ea-99ae-233de230c85a.png)

**Comment by ypid** [comment]
Hi

You are welcome. Not sure how I could use the wrong TeX length. I guess I just don’t use twocolumn layouts so I did not notice.

I will make a release in a few weeks with this fix included. Thanks you!
