### ISSUE TITLE
Deprecate and remove fallback license. Hard fail if no license if give.

### ISSUE THREAD

**Issue by ypid** [ypid/latex-packages#51]
From: https://github.com/ypid/latex-packages/issues/48#issuecomment-612848817

> by the way, shouldn't the default license be version 4.0 instead of 3.0?

As the documentation mentions it, no one should just load this package and let the package choose what license to put the document under. I don’t want to have that power to randomly update the license version of documents :)

I guess this default value is a misfeature. I suggest I deprecate it slowly. First make it emit a warning at compile time. Then make it hard fail at compile time.

CC:  @rodrigoalcarazdelaosa

**Comment by ypid** [comment]
Those options will be soft required starting with v2.0.0. And become hard required in an upcoming major version of the package, with the earliest release in 2021-07 to give people time to migrate.

**Comment by ypid** [comment]
> by the way, shouldn't the default license be version 4.0 instead of 3.0?

@rodrigoalcarazdelaosa And now the actual answer to your question. I finally updated the examples in the manual to v4.0. Thanks for the hint again.

**Comment by rodrigoalcarazdelaosa** [comment]
> > by the way, shouldn't the default license be version 4.0 instead of 3.0?
> 
> @rodrigoalcarazdelaosa And now the actual answer to your question. I finally updated the examples in the manual to v4.0. Thanks for the hint again.

Thanks to you for this great package!
