### ISSUE TITLE
Retired CC licenses

### ISSUE THREAD

**Issue by 1q2w3e4r5t6z7u** [ypid/latex-packages#52]
What about adding the [retired](https://creativecommons.org/retiredlicenses) CC licenses? I. e., [CC ND 1.0](https://creativecommons.org/licenses/nd/1.0/), [CC ND-NC 1.0](https://creativecommons.org/licenses/nd-nc/1.0/), [CC NC 1.0](https://creativecommons.org/licenses/nc/1.0/), [CC NC-SA 1.0](https://creativecommons.org/licenses/nc-sa/1.0/), and  [CC SA 1.0](https://creativecommons.org/licenses/sa/1.0/).

**Comment by ypid** [comment]
I don’t have a need and I am not sure many others would. Feel free to open a pull request.

**Comment by ypid** [comment]
Hi again, I due to #53 I had to think more about how to handle retired licenses. I added a "Retired licenses" section where I put down my thoughts. https://github.com/ypid/latex-packages/commit/88ea7f9e1ef28bc8b7104a466e5edeb6775a2d30 Input is welcome.

**Comment by ypid** [comment]
Seems like there is no need for those older licenses. I am closing this issue for now.
