### ISSUE TITLE
doclicense: spurious text "not found" in one image file

### ISSUE THREAD

**Issue by nbeisert** [ypid/latex-packages#56]
Minor bug: There is some spurious text "not found" in the image file "doclicense-CC-pd-88x31"

**Comment by ypid** [comment]
CC PD is long deprecated and was removed from doclicense with v2.0.0 (ref: #53). I looked into this out of interested. The SVG file that I use to generate the PDF and EPS file from using Inkscape is good. Inkscape also shows the "not found" when I open the SVG. I tested with 1.0.1 from buster-backports. Same issue.

I removed the deprecated PD files from the project.
