### ISSUE TITLE
doclisence running make error

### ISSUE THREAD

**Issue by siefkenj** [ypid/latex-packages#6]
I forked doclicense, but running a `make clean` and a `make` in the doclicense directory produces the error:

    ! LaTeX Error: File `doclicense-CC-by-sa' not found.

Is there a trick to fixing this?  If I symlink the file from images to the current directory, it works, but `make clean` deletes my symlink.

**Comment by ypid** [comment]
I am guessing you had not installed doclicense? Does https://github.com/ypid/latex-packages/commit/21db2fbb2da28ea3f9112ecd91f365e26fb6b874 fix the issue for you? If not please reopen :smile:

**Comment by siefkenj** [comment]
I tried doing `export TEXMFHOME=$PWD` and running `make` again.  No luck.  `export TEXMFHOME=$PWD/images` didn't work either.  Could you be a little more explicit about how to get it to compile?  (You're correct, I don't have the doclicense installed.)

**Comment by ypid** [comment]
I forgot to mention that `export TEXMFHOME="$PWD"` would not work because a TEXMF tree needs to have a certain structure. Fixed.

**Comment by siefkenj** [comment]
That works!  Would it make sense to have the makefile `mkdir -p tex/latex; ln -s $PWD tex/latex/` and then compile with `$TEXMFHOME` set to `$PWD`?  This way nobody would need to be confused if they just wanted to test-build but didn't know much about tex.

**Comment by ypid** [comment]
I added an `install` target which installs into `TEXMFHOME`.
