### ISSUE TITLE
doclicense documentation pdf corrupted

### ISSUE THREAD

**Issue by ArTourter** [ypid/latex-packages#61]
it seems the doclicense.pdf file on ctan is corrupted: when opening it with Adobe reader (version 9.5.5 on linux or version 11.x on windows at least) one gets the error when reaching page 4:

`There is an error processing a page. There was a problem reading this document (131)`

I have tried to recompile it myself and get the same problem. However, compiling another document using the doclicense package, I haven't been able to get the same problem.

I tried also compiling the doclicense.dtx using lualatex instead, and that work fine.

the pages in doclicense.pdf that seem to be causing problems are the ones with images embedded, so there might be an issue with some of the graphics which bugs out pdflatex but I cannot trace it.

**Comment by ypid** [comment]
> reaching page 4

For the latest version on CTAN (currently) 2.0.1, the graphics start on page 5. But I guess you mean some kind of pre-loading takes place which is imaginable.

I have no Adobe reader laying around/installed for quick testing. I test with Evince. Quick search says that both of these versions are a bit old (ref: https://en.wikipedia.org/wiki/Adobe_Acrobat_version_history). Are there more current versions you can try? For Windows, this seems to be the package to use https://chocolatey.org/packages/adobereader. Anyway, I prepared a few test PDFs you can try. The commit is signed with my normal OpenPGP key for commits:

https://github.com/ypid/latex-packages/commit/86e7bfc28614722d3ee1ad1dfb7502791bc0e1f1#diff-8cd31fb4e086a07e1e49016b8492885b

**Comment by ArTourter** [comment]
Hi Thanks for doing this.

I know the versions of adobe reader are old. Well the linux one is the latest and last one available unfortunately so this is what I have. The windows version was the one installed on my work remote desktop so I couldn't change it either.

I have tried the files you created and both pdflatex created one fail the same way. The lualatex one works as mine did.

I have also installed the latest version of adobe reader DC on a windows machine I had lying around and the pdflatex version (the original one) works fine.

Another note: I reverted the texlive package to the previous one (document dated 27th May) and that version doesn't have the problem. However, I cannot see anything to the commits that would explain this: doesn't look like the images haven't changed or anything. but I tried to compile the current version on a slightly out of date version of texlive2020 (the one provided by my distro) and the problem occurs.

I also tried to compile the previous version of the document (from version 2.0.0) using both an uptodate texlive2020 and the slightly out of date one, and they work fine in all cases. But again, i looked at the diff of the two sources and nothing jumps out nor does the log show anything is a miss.

maybe it is something in the layout that triggers a bug in pdflatex, but if that is the case I am not sure where to look nor have I got enough knowldege of pdf to trace it.

**Comment by ypid** [comment]
> The windows version was the one installed on my work remote desktop so I couldn't change it either.

Work windows admins don’t have their update management together. Say no more ;-)

> Another note: I reverted the texlive package to the previous one (document dated 27th May) and that version doesn't have the problem. However, I cannot see anything to the commits that would explain this: doesn't look like the images haven't changed or anything.

This is something we can work with. Can you run a git bisect to find the exact change that introduced the regression. From looking at the diff, the more invasive change is the switch to proper ISO 8601 dates using the `isodate` package. Don’t forget to generate the sty file :)


Concluding, I guess I can use switch to using LuaLaTeX. It prefer it anyway. What do you think?
