### ISSUE TITLE
[doclicense] Add metadata (XMP) in PDF file

### ISSUE THREAD

**Issue by rugk** [ypid/latex-packages#63]
CC says you can use `XMP`  data and embed that in a PDF that then specifies in a machine-readable way the license of the document.

See https://wiki.creativecommons.org/wiki/XMP

It would be awesome if this would me more than human-readable. :slightly_smiling_face:

**Comment by ypid** [comment]
doclicense uses `hyperxmp` already. You can test this with Evince for example [doclicense.pdf](http://mirrors.ctan.org/macros/latex/contrib/doclicense/doclicense.pdf). Can we do even more for machine-readable?

**Comment by rugk** [comment]
hmm in my own document I don't see anything like that in _evince_:
![grafik](https://user-images.githubusercontent.com/11966684/92132045-f2dcea00-ee06-11ea-8351-a1c982d9dcb0.png)

**Comment by ypid** [comment]
There is a new tab onto that most other documents I read don’t have.

![Untitled](https://user-images.githubusercontent.com/1301158/92161336-c76ef500-ee30-11ea-9261-e7b4f47e95d2.png)

**Comment by rugk** [comment]
Ahhh, now I see what you mean.

Hmm, in my case this does not work though.
(Only the `doclicense.pdf` example works.)

Also created an STR document on Overleaf now (TexLive 2019, tested with pdfLaTex and LuaLaTex): https://www.overleaf.com/read/stswtcrprwnz

[doclicense_pdfLaTex.pdf](https://github.com/ypid/latex-packages/files/5188595/doclicense_test.pdf)
[doclicense_LuaLaTex.pdf](https://github.com/ypid/latex-packages/files/5188596/doclicense_test-1.pdf)

I see no such tab there when I view this in Evince.

**Comment by ypid** [comment]
Have you loaded the package `hyperxmp` as the documentation tells you to :wink: ?

**Comment by rugk** [comment]
Ohhh, my bad. IMHO if you load `hyperref` you can also load `hyperxml` by default. I see no reason to not to do so and add metadata by default.

**Comment by ypid** [comment]
Thanks for your feedback! I created #65 which should address it all :wink: . hyperxmp is optional so we don’t need to hard fail when it is not installed. A warning is enough. With this, I agree with you that loading it by default is preferred. I have done plenty of (user) testing of the package over the years.
