### ISSUE TITLE
Adding license fulltext

### ISSUE THREAD

**Issue by siefkenj** [ypid/latex-packages#7]
I'd like to add the ability to include the fulltext of each license, but I'm not sure where files can be placed such that they can be included with `\input` once the package is installed. Can you give me any guidance on this?

**Comment by ypid** [comment]
Nice idea. This can be done the same way as with the images. I would suggest creating a directory like `license_texts` and create a text file called ` doclicense-text-CC-by.tex`.

**Comment by siefkenj** [comment]
So all subfolders are automatically searched by `\input`?

**Comment by ypid** [comment]
No, but because the `license_texts` directory is also going to end up in the texmf tree, it will be used.

**Comment by siefkenj** [comment]
I thought this would be easy, but it's becoming somewhat of a nightmare.  I have in a subdirectory a file named `CC-by-sa-3.0-fulltext.tex`, and I am attempting to include it with `\include{\doclicenseType-\doclicense@modifier-\doclicenseVersion-fulltext}`, but that fails.  When I use `\message{}` to try and print out what `\doclicenseType-\doclicense@modifier-\doclicenseVersion-fulltext` expands to, I get

    CC\protect \let \futurelet \@let@token \let \let \@xspace@maybespace \relax -by-sa-3.0\protect \let  \futurelet \@let@token \let \let \@xspace@maybespace \relax -fulltext

I'm not sure where to go from here...

**Comment by ypid** [comment]
There is a difference between `\input` and `\include`. You need to use `\input`  here. Does that work?

**Comment by siefkenj** [comment]
I've tried them both.  Neither work.  If I hardcode `\input{CC-by-sa-3.0-fulltext}` it works though.

**Comment by ypid** [comment]
Works for me … Have you written a Makefile or something to download all license texts?

**Comment by ypid** [comment]
I am on it :wink:

**Comment by ypid** [comment]
All right. Added plain text licenses. But that does not quite satisfy the typesetter in me so I need to parse https://creativecommons.org/licenses/by-sa/3.0/legalcode and convert it into LaTeX :wink:

**Comment by ypid** [comment]
LibreOffice with Writer2LaTeX seems to work best for this: https://creativecommons.org/licenses/by/3.0/legalcode

But it can not be automated this way. Looking into other ways.

**Comment by ypid** [comment]
All right. Should be done. Want to test it? Feel free to submit patches when you need more features. I guess this calls for a new release of doclicense soon.

**Comment by siefkenj** [comment]
Great!  I'll test it as soon as I have a free moment.  I was originally envisioning parsing the plaintext as markdown and then converting that to latex as an automated process, but the plaintext would need some pre-processing for that to work.

**Comment by ypid** [comment]
plaintext -> Markdown/LaTeX: I also had that idea but it would have been every hard work. I kind of started writing regexes for that but then realized that there are better ways to do it :wink:

**Comment by siefkenj** [comment]
Works great!  I sent a PR with some improvements :-)
