### ISSUE TITLE
doclicense: Token not allowed in a PDF string (Unicode):(hyperref) removing `\enquote'

### ISSUE THREAD

**Issue by thbde** [ypid/latex-packages#80]
Following the documentation https://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/macros/latex/contrib/doclicense/doclicense.pdf
![image](https://user-images.githubusercontent.com/4573481/123704685-3907ac00-d866-11eb-86d6-f6e20d978e19.png)
I create a new document:

```latex
\documentclass[a4paper]{report}
\usepackage{
	babel,
}
\usepackage[
type={CC},
modifier={by-sa},
version={4.0},
]{doclicense}
\begin{document}
Thanks for your great work with doclicense!
\end{document}
```

Which produces the warning:

> Token not allowed in a PDF string (Unicode):(hyperref) removing `\enquote'

`\listfiles` output:

> Package: doclicense 2021/03/13 v2.3.0

Expectation: I get no warning following the documentation.

The warning goes away if I explicitly load the `hyperref `package (or the `hyperxmp `package which may also load the `hyperref `package):
```latex
\documentclass[a4paper]{report}
\usepackage{
	babel,
}
\usepackage[
type={CC},
modifier={by-sa},
version={4.0},
]{doclicense}
%the following line is new
\usepackage{hyperref}
\begin{document}
Thanks for your great work with doclicense!
\end{document}
```

**Comment by ypid** [comment]
https://tex.stackexchange.com/questions/312935/i-need-some-help-ordering-these-imports-so-the-hyperref-package-works-properly says csquotes before hyperref. General rule as I remember it is hyperref should be last. But same as in your case, loading csquotes after hyperref avoids the warning. So lets go with that.
