### ISSUE TITLE
content of \doclicenseLongText not suitable for pdfcopyright key

### ISSUE THREAD

**Issue by u-fischer** [ypid/latex-packages#86]
doclicense calls

~~~~
  \hypersetup{%
      pdfcopyright  = {\doclicenseLongText},
      pdflicenseurl = {\doclicenseURL},
    }
~~~~

`\doclicenseLongText`  is define as

~~~~
\newcommand{\doclicenseLongText}{%
  \doclicense@lang@thisDoc\space
  \href{\doclicenseURL}{\doclicenseLongType\space\enquote{\doclicense@longName}}%
  \doclicense@lang@word@license.\xspace%
}
~~~~

That is a rather fragile setup as it relies on a specific expansion behaviour which can change in the future (and actually it currently breaks if the new pdfmanagement of latex is active).

I would suggest to use as pdfcopyright value a text that doesn't contain typesetting commands and no \href.

**Comment by ypid** [comment]
Thanks for reporting! I propose #87 to fix it. The advantage was that this prevented having duplicate code. I agree with you that the code is fragile and this is a good opportunity to fix it.

**Comment by u-fischer** [comment]
Thanks. And just to be clear: the actual error which lead to this report was due to a bug in my patches of hyperxmp in the pdfmanagement. It didn't pass the copyright message correctly through `\pdfstringdef`. But on the whole I think it is better to avoid potentially fragile code in such places if possible. User can always redefine typesetting commands like `\enquote`.

**Comment by ypid** [comment]
Thanks for the info. Then it is not affecting users and I can post-pone releasing this.
