### ISSUE TITLE
Clarify in documentation how to use CC0

### ISSUE THREAD

**Issue by Morpheu5** [ypid/latex-packages#96]
It isn't obvious from the docs that, to use CC0, one has to specify `zero` as a modifier. I had to [ask on Stack Exchange](https://tex.stackexchange.com/questions/667737/how-can-i-specify-a-cc0-1-0-license-with-doclicense/667738#667738) :)

Thanks for an otherwise great package!

**Comment by ypid** [comment]
Wanna give it a try with a pull request :) ?
